version: '2'
services:
  db:
    image: 'postgres:10.1-alpine'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ../reviewer-data/postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  redis:
    image: 'redis:5.0-alpine'
    ports:
      - "${REDIS_PORT}:6379"
